server:
  port: 8183

spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost

integration:
  payroll:
    base-url: http://localhost:8184
    connect-timeout: 5
    read-timeout: 5
    payroll:
      url: ${integration.payroll.base-url}/api/v1/payroll/employee

logging:
  level:
    org.apache.http: TRACE